import type { Product } from "./types";
const seeds = [
  [
    "Blusa Alba",
    "ropa",
    "Marfil",
    "CH",
    590,
    6,
    "blouse",
    "Una silueta ligera y atemporal. Blusa de muestra para explorar el catálogo.",
  ],
  [
    "Arracadas Aura",
    "joyeria",
    "Dorado",
    "",
    320,
    8,
    "earrings",
    "Un detalle sutil que transforma tu día. Pieza de demostración.",
  ],
  [
    "Eau de Lumière",
    "perfumes",
    "",
    "50 ml",
    890,
    4,
    "perfume",
    "Notas suaves y un frasco esencial. Perfume ficticio de demostración.",
  ],
  [
    "Blusa Alba · Edición natural",
    "ropa",
    "Natural",
    "M",
    590,
    0,
    "blouse",
    "La misma esencia, una nueva combinación. Producto de demostración.",
  ],
  [
    "Arracadas Sol",
    "joyeria",
    "Dorado",
    "",
    390,
    2,
    "earrings",
    "Acabado luminoso y líneas sencillas. Pieza de demostración.",
  ],
  [
    "Lumière · Esencia",
    "perfumes",
    "",
    "100 ml",
    1290,
    3,
    "perfume",
    "Un aroma para acompañarte. Producto ficticio de demostración.",
  ],
];
export function demoProducts(): Product[] {
  return seeds.map((s, i) => ({
    id: `demo-${i}`,
    name: String(s[0]),
    description: String(s[7]),
    brand: "Colección de muestra",
    category_id: String(s[1]),
    gender: i === 2 ? "Unisex" : "Mujer",
    published: true,
    revision: 1,
    created_at: new Date(2026, 8, 17 - i).toISOString(),
    variants: [
      {
        id: `v-${i}`,
        sku: `DUN-00${i + 1}`,
        barcode: `00010000${i + 1}`,
        color: String(s[2]),
        size: s[1] === "ropa" ? String(s[3]) : "",
        presentation: s[1] === "perfumes" ? String(s[3]) : "",
        price: Number(s[4]),
        stock: Number(s[5]),
        active: true,
        cost: 120,
      },
    ],
    photos: [
      {
        id: `ph-${i}`,
        product_id: `demo-${i}`,
        path: `/demo/${s[6]}.png`,
        url: `/demo/${s[6]}.png`,
        position: 0,
      },
    ],
  }));
}
